version: '2'

services:
  proxysql:
    build: proxysql
    depends_on:
      - mysql
    expose:
      - 3306
    volumes:
     - ".:/root"
    command: /usr/bin/proxysql -f -c /root/proxysql.conf --initial && /usr/bin/proxysql -f -c /root/proxysql.conf

  mysql:
    image: percona:5.5
    expose:
      - 3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: proxysql_test
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    command: --transaction-isolation=REPEATABLE-READ --character-set-server=utf8 --collation-server=utf8_unicode_ci

  test:
    build: test
    depends_on:
      - proxysql
    command: python3.5 /mnt/test.py
    volumes:
      - ".:/mnt"
